services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - attendance_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - attendance_network

  attendance_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://attendance_user:attendance_password@postgres:5432/attendance_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - CAMERA_URLS=${CAMERA_URLS:-0}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@company.com}
      - MANAGER_EMAIL=${MANAGER_EMAIL:-manager@company.com}
      - ENVIRONMENT=production
      - FACE_RECOGNITION_TOLERANCE=0.6
      - FACE_DETECTION_MODEL=hog
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    devices:
      - /dev/video0:/dev/video0  # For webcam access
    privileged: true  # Required for camera access in Docker
    depends_on:
      - postgres
      - redis
    networks:
      - attendance_network
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://attendance_user:attendance_password@postgres:5432/attendance_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@company.com}
      - MANAGER_EMAIL=${MANAGER_EMAIL:-manager@company.com}
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - attendance_network
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A app.tasks.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://attendance_user:attendance_password@postgres:5432/attendance_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key-change-in-production
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@company.com}
      - MANAGER_EMAIL=${MANAGER_EMAIL:-manager@company.com}
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - attendance_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  attendance_network:
    driver: bridge